.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

/* Handwritten function */
nonmatching entrypoint, 0x38

glabel entrypoint
    /* 1000 80200050 3C088025 */  lui        $t0, %hi(main_BSS_START)
    /* 1004 80200054 3C090003 */  lui        $t1, (0x306C0 >> 16)
    /* 1008 80200058 25086D70 */  addiu      $t0, $t0, %lo(main_BSS_START)
    /* 100C 8020005C 352906C0 */  ori        $t1, $t1, (0x306C0 & 0xFFFF)
  .L80200060:
    /* 1010 80200060 2129FFF8 */  addi       $t1, $t1, -0x8 /* handwritten instruction */
    /* 1014 80200064 AD000000 */  sw         $zero, 0x0($t0)
    /* 1018 80200068 AD000004 */  sw         $zero, 0x4($t0)
    /* 101C 8020006C 1520FFFC */  bnez       $t1, .L80200060
    /* 1020 80200070 21080008 */   addi      $t0, $t0, 0x8 /* handwritten instruction */
    /* 1024 80200074 3C0A8023 */  lui        $t2, %hi(main)
    /* 1028 80200078 3C1D8028 */  lui        $sp, %hi(D_80282B60)
    /* 102C 8020007C 254A1150 */  addiu      $t2, $t2, %lo(main)
    /* 1030 80200080 01400008 */  jr         $t2
    /* 1034 80200084 27BD2B60 */   addiu     $sp, $sp, %lo(D_80282B60)
endlabel entrypoint
    /* 1038 80200088 00000000 */  nop
    /* 103C 8020008C 00000000 */  nop
    /* 1040 80200090 00000000 */  nop
    /* 1044 80200094 00000000 */  nop
    /* 1048 80200098 00000000 */  nop
    /* 104C 8020009C 00000000 */  nop
